"""Where does the heterogeneity live?

05 rejected the one-parameter random-effects model: six different functionals of
the same 1,252 models imply taus from 0.0012 to 0.0160, a 13x spread, whereas the
same six functionals agree to 3 decimal places on data actually generated by that
model. So the models are NOT exchangeable draws around one true effect.

Two candidate structures, both testable here:

  (H-precision) heterogeneity is concentrated among the PRECISE models. Would
      mean the imprecise models are pure noise contributing nothing but variance,
      and the real disagreement is among the models that can actually see
      something.

  (H-estimand) heterogeneity is between ESTIMANDS, not between researchers.
      Teams chose among 11 dependent variables, 3 immigration measures
      (stock / flow / change-in-flow), different country sets, and total vs
      within vs between country effects. Those choices change the quantity being
      estimated (Lundberg, Johnson & Stewart 2021, 'What is your estimand?').
      If conditioning on them absorbs the heterogeneity, then 'idiosyncratic
      researcher variability' is a residual against a null that assumed all
      1,253 models answer the same question.

This is the same structure as Jo, Garg & Raghavan (2026) on LLM monoculture,
recorded here as paper:jo2026-subjectivity: a discrepancy measured against a
null the analyst chose, where a richer null absorbs it. Neither literature cites
the other.
"""
import os
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data", "cri_model_level.csv")
Z95 = 1.959964


def pm(y, v, it=200):
    """Paule-Mandel tau^2."""
    if len(y) < 3:
        return np.nan
    lo, hi = 0.0, max(1e-12, np.var(y, ddof=1) * 50)

    def gq(t2):
        w = 1 / (v + t2)
        mu = (w * y).sum() / w.sum()
        return (w * (y - mu) ** 2).sum() - (len(y) - 1)
    if gq(lo) <= 0:
        return 0.0
    if gq(hi) > 0:
        return hi
    for _ in range(it):
        mid = 0.5 * (lo + hi)
        if gq(mid) > 0:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)


def load():
    d = pd.read_csv(DATA, low_memory=False)
    a = d[d.AME_Z.notna() & (d.u_teamid != 0)].copy()
    a["se_z"] = (a.upper_Z - a.lower_Z) / (2 * Z95)
    a = a[np.isfinite(a.se_z) & (a.se_z > 0)].copy()
    a["v"] = a.se_z ** 2
    return a


def main():
    a = load()
    y, v = a.AME_Z.values, a.v.values
    print("H-PRECISION: tau estimated within quintiles of the standard error")
    q = pd.qcut(a.se_z, 5, labels=False)
    rows = []
    for k in range(5):
        m = (q == k).values
        t2 = pm(y[m], v[m])
        rows.append((k + 1, m.sum(), np.median(a.se_z[m]), np.sqrt(t2),
                     np.sqrt(t2) / np.median(a.se_z[m]),
                     np.std(y[m], ddof=1)))
    print(pd.DataFrame(rows, columns=["SE quintile", "n", "median SE", "tau",
                                      "tau/median SE", "SD(estimates)"])
          .to_string(index=False, float_format=lambda x: "%.5f" % x))
    print("  Reading: if tau is roughly CONSTANT across quintiles the models are")
    print("  exchangeable; if tau tracks the SE, the 'heterogeneity' is a scale")
    print("  effect; if tau/SE is far above 1 only in the precise quintiles, the")
    print("  disagreement is real and only visible where precision allows it.\n")

    print("H-ESTIMAND: how much heterogeneity survives conditioning on the")
    print("choices that change the estimand?")
    strata = [
        ("none (all models pooled)", []),
        ("DV", ["DV"]),
        ("immigration measure", ["main_IV_type"]),
        ("DV x immigration measure", ["DV", "main_IV_type"]),
        ("DV x measure x effect type", ["DV", "main_IV_type", "main_IV_effect"]),
        ("DV x measure x effect x n countries",
         ["DV", "main_IV_type", "main_IV_effect", "num_countries"]),
        ("team (for contrast: NOT an estimand choice)", ["u_teamid"]),
    ]
    print("%-46s %5s %6s %9s %9s" % ("conditioning set", "cells", "n>=3",
                                     "pooled tau", "% of base"))
    base = None
    for name, keys in strata:
        if not keys:
            t = np.sqrt(pm(y, v))
            base = t
            print("%-46s %5d %6d %9.5f %8.1f%%" % (name, 1, 1, t, 100.0))
            continue
        g = a.groupby(keys)
        t2s, ns = [], 0
        for _, sub in g:
            if len(sub) < 3:
                continue
            t2 = pm(sub.AME_Z.values, sub.v.values)
            if np.isfinite(t2):
                t2s.append((len(sub), t2))
                ns += 1
        # pooled within-cell tau^2, weighted by cell size
        tot = sum(n for n, _ in t2s)
        t2p = sum(n * t for n, t in t2s) / tot
        print("%-46s %5d %6d %9.5f %8.1f%%"
              % (name, g.ngroups, ns, np.sqrt(t2p), 100 * np.sqrt(t2p) / base))

    print("\n  A drop means the choice defines a different estimand and the")
    print("  variation it produces is not 'idiosyncratic'. A non-drop means the")
    print("  variation is inside the choice, i.e. genuinely unexplained.")

    print("\nCROSS-CHECK: the same conditioning applied to the CONCLUSION spread")
    w = a.groupby("u_teamid").u_teamid.transform("size").rdiv(1.0).values
    lo, hi = y - Z95 * np.sqrt(v), y + Z95 * np.sqrt(v)
    cat = np.where(hi < 0, "neg", np.where(lo > 0, "pos", "ns"))
    a2 = a.assign(cat=cat, w=w)
    print("  overall (weighted): "
          + str({k: round(100 * vv, 2) for k, vv in
                 a2.groupby("cat").w.sum().div(a2.w.sum()).items()}))
    for keys in (["DV"], ["main_IV_type"]):
        print("  by %s:" % keys[0])
        tb = a2.groupby(keys + ["cat"]).w.sum().unstack(fill_value=0)
        tb = 100 * tb.div(tb.sum(1), axis=0)
        print(tb.round(1).to_string())

    print("\nHOW BIG IS THE DISAGREEMENT WHERE IT IS BEST MEASURED?")
    m = (a.se_z <= a.se_z.quantile(0.2)).values
    t = np.sqrt(pm(y[m], v[m]))
    print("  most precise quintile (n=%d, median SE %.5f): tau = %.5f"
          % (m.sum(), np.median(a.se_z[m]), t))
    print("  90%% of true effects among these models lie in [%+.4f, %+.4f]"
          % (-1.645 * t, 1.645 * t))
    print("  Cohen's benchmark for a 'small' standardized effect is 0.10-0.20.")


if __name__ == "__main__":
    main()
