#!/usr/bin/env python3
"""r06 -- the break test.  Generate data in which, BY CONSTRUCTION, there is no
unhappy minority, no threshold, and no subpopulation whose response to income
differs from anyone else's -- then run KKM's own Table 1 procedure on it and ask
whether the procedure reports "flattening restricted to the least happy 20%".

CONTRIBUTING.md rule 3: feed the analysis a case where you know the answer, with
the effect forced in AND with the effect absent.

Four generators, all with the SAME income distribution as the real data (the 15
observed category values with their observed counts) and the same n = 33,391:

  NULL-LOC    y = a + b*L + sigma * eps                 sigma CONSTANT
              -> pure location shift. Homogeneity holds exactly. KKM's estimator
                 must NOT report flattening. Negative control.

  LS-LIN      y = a + b*L + exp(s0 + s1*L) * eps        one log-linear scale term
  LS-QUAD     y = a + b*L + exp(s0 + s1*L + s2*L^2)*eps smooth, NO threshold
  LS-PIECE    y = a + b*L + exp(s0 + s1*L + s2*(L-k)+)*eps   scale break at 100k

  In every one of them the LOCATION is linear in log(income) with a single slope b,
  the same for every person. Nobody is in a subpopulation. Nobody has a threshold.

If LS-QUAD reproduces KKM Table 1 -- flat above $100k at tau .05/.10/.15,
significant at .25/.30/.35, acceleration at .85 -- then the paper's headline
qualitative finding is fully generated by a smooth change in the WIDTH of the
happiness distribution, and its interpretation ("the miseries that remain are not
alleviated by high income ... heartbreak, bereavement, and clinical depression")
does not follow from the evidence offered for it.

Parameters are estimated from the real data (r04/r05), not invented.

Output: out_simulation.csv, and a printed rate table.
"""
import os
import sys
import warnings

import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.regression.quantile_regression import QuantReg
from statsmodels.tools.sm_exceptions import IterationLimitWarning

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
warnings.simplefilter("ignore", IterationLimitWarning)

HERE = os.path.dirname(os.path.abspath(__file__))
CSV = os.path.join(HERE, "..", "artifacts", "kkm2023.csv")
LOW = [0.05, 0.10, 0.15]
HIGH = [0.25, 0.30, 0.35]
KNOT = np.log(100000.0)
NSIM = int(os.environ.get("NSIM", 200))
SEED = 20260902


def kkm_table1(y, L, A):
    """KKM's estimator: one quantile regression per tau with an income>100k
    interaction; slope above = b1+b3, its se from the 2x2 block of the cov."""
    out = {}
    X = np.column_stack([np.ones(len(y)), L, A, L * A])
    for t in LOW + HIGH + [0.85]:
        r = QuantReg(y, X).fit(q=t, max_iter=2000)
        V = r.cov_params()
        b = r.params[1] + r.params[3]
        se = float(np.sqrt(max(V[1, 1] + V[3, 3] + 2 * V[1, 3], 1e-12)))
        out[t] = {"above": b, "p_above": 2 * (1 - stats.norm.cdf(abs(b / se))),
                  "inter": r.params[3], "p_inter": r.pvalues[3],
                  "below": r.params[1]}
    return out


def verdict(res):
    flat = all(res[t]["p_above"] > 0.05 for t in LOW)
    bnd = all(res[t]["p_above"] < 0.05 for t in HIGH)
    accel = res[0.85]["p_inter"] < 0.05 and res[0.85]["inter"] > 0
    return flat, bnd, accel


def fit_generators(d):
    """Estimate every generator's parameters from the real data."""
    y = d.wellbeing.values
    L = np.log(d.income.values)
    Lc = L - L.mean()
    # location: single linear median slope, no knot (r05 Part B: curvature ~ 0)
    r = QuantReg(y, np.column_stack([np.ones(len(y)), Lc])).fit(q=0.5)
    a, b = r.params
    resid = y - (a + b * Lc)
    # scale by income category, as log sd
    g = pd.DataFrame({"L": L, "Lc": Lc, "r": resid}).groupby("L")["r"]
    sd = g.std(ddof=1)
    n = g.size()
    Lg = sd.index.values
    Lgc = Lg - L.mean()
    w = n.values - 1.0                       # precision of a log-sd is ~ (n-1)/2
    gens = {}
    gens["NULL-LOC"] = (a, b, np.array([np.log(np.sqrt((w * sd.values ** 2).sum() / w.sum()))]),
                        lambda Lc_, p: np.full_like(Lc_, np.exp(p[0])))
    for name, basis in (
            ("LS-LIN", lambda x: np.column_stack([np.ones(len(x)), x])),
            ("LS-QUAD", lambda x: np.column_stack([np.ones(len(x)), x, x ** 2])),
            ("LS-PIECE", lambda x: np.column_stack(
                [np.ones(len(x)), x, np.maximum(x - (KNOT - L.mean()), 0)]))):
        Xg = basis(Lgc)
        W = np.diag(w)
        p = np.linalg.solve(Xg.T @ W @ Xg, Xg.T @ W @ np.log(sd.values))
        gens[name] = (a, b, p, lambda Lc_, p=p, basis=basis: np.exp(basis(Lc_) @ p))
    eps = resid / np.interp(Lc, Lgc, sd.values)     # standardised empirical errors
    eps = (eps - eps.mean()) / eps.std(ddof=1)
    return gens, eps, L.mean()


def main():
    d = pd.read_csv(CSV)
    y = d.wellbeing.values
    L = np.log(d.income.values)
    A = (d.income.values > 100000).astype(float)
    n = len(d)

    real = kkm_table1(y, L, A)
    rf, rb, ra = verdict(real)
    print("REAL DATA:  flat_bottom=%s  boundary20=%s  accel_top=%s" % (rf, rb, ra))
    print("            above-100k slopes  " + "  ".join(
        "t=%.2f:%.2f(p=%.3f)" % (t, real[t]["above"], real[t]["p_above"])
        for t in LOW + HIGH))
    print()

    gens, eps_pool, Lbar = fit_generators(d)
    Lc = L - Lbar
    for name, (a, b, p, sfun) in gens.items():
        s = sfun(Lc, p) if name == "NULL-LOC" else sfun(Lc)
        print("generator %-9s  location slope b=%.3f   sigma range %.2f..%.2f"
              % (name, b, np.min(s), np.max(s)))
    print("\nrunning %d simulations per generator (empirical error distribution, "
          "then a normal-error replicate of the decisive one)\n" % NSIM)

    rng = np.random.default_rng(SEED)
    rows = []
    for name, (a, b, p, sfun) in gens.items():
        s = sfun(Lc, p) if name == "NULL-LOC" else sfun(Lc)
        loc = a + b * Lc
        cnt = {"flat": 0, "bnd": 0, "accel": 0, "all3": 0, "kkm_pattern": 0}
        slopes15, slopes30 = [], []
        for it in range(NSIM):
            e = rng.choice(eps_pool, size=n, replace=True)
            ysim = loc + s * e
            res = kkm_table1(ysim, L, A)
            f, bd, ac = verdict(res)
            cnt["flat"] += f
            cnt["bnd"] += bd
            cnt["accel"] += ac
            cnt["all3"] += f and bd and ac
            cnt["kkm_pattern"] += f and bd
            slopes15.append(res[0.15]["above"])
            slopes30.append(res[0.30]["above"])
        rows.append({"generator": name, "nsim": NSIM,
                     "rate_flat_bottom": cnt["flat"] / NSIM,
                     "rate_boundary20": cnt["bnd"] / NSIM,
                     "rate_accel_top": cnt["accel"] / NSIM,
                     "rate_kkm_pattern": cnt["kkm_pattern"] / NSIM,
                     "rate_all_three": cnt["all3"] / NSIM,
                     "mean_slope_above_t15": np.mean(slopes15),
                     "mean_slope_above_t30": np.mean(slopes30),
                     "real_slope_above_t15": real[0.15]["above"],
                     "real_slope_above_t30": real[0.30]["above"]})
        print("%-9s  flat_bottom %5.1f%%   boundary20 %5.1f%%   accel_top %5.1f%%"
              "   KKM pattern (flat+boundary) %5.1f%%   all three %5.1f%%"
              "   | mean above-slope  t=.15 %.2f (real %.2f)  t=.30 %.2f (real %.2f)"
              % (name, 100 * cnt["flat"] / NSIM, 100 * cnt["bnd"] / NSIM,
                 100 * cnt["accel"] / NSIM, 100 * cnt["kkm_pattern"] / NSIM,
                 100 * cnt["all3"] / NSIM,
                 np.mean(slopes15), real[0.15]["above"],
                 np.mean(slopes30), real[0.30]["above"]), flush=True)

    out = pd.DataFrame(rows)
    out.to_csv(os.path.join(HERE, "out_simulation.csv"), index=False)
    print("\nwrote out_simulation.csv")
    print("\nREADING THIS TABLE")
    print("  NULL-LOC is the negative control. A high 'flat_bottom' rate there would")
    print("  mean the estimator invents flattening out of nothing, and everything")
    print("  else here would be uninterpretable. A LOW rate there plus a HIGH rate")
    print("  for LS-QUAD is the finding: no threshold, no subpopulation, and KKM's")
    print("  reported pattern anyway.")


if __name__ == "__main__":
    main()
