"""THE DECISIVE TEST -- parametric bootstrap ("clone") model check.

The real MPE-92M split-half congruence profile decays smoothly (k=12:
.90 .88 .86 .85 .83 .81 .78 .75 .71 .64 .55 .39) with NO cliff, and no factor
reaches the .95 "factors are equal" criterion at any k >= 5.

Two rival explanations, and they demand opposite conclusions:

  H1 MISSPECIFICATION. The data are not generated by a k-factor model with
     discrete factors; "how many factors" is the wrong question about this
     object, not merely a threshold-dependent one.
  H2 ESTIMATION NOISE. There ARE k discrete factors; loadings are simply
     weaker than in my synthetic cases, so at n=701 per half nothing can
     reach .95. Nothing interesting is happening.

They are distinguished by a CLONE: fit the k-factor model to all N=1403, then
generate a synthetic dataset from that fitted loading matrix, at the same N,
same k, same item count. The clone is BY CONSTRUCTION a true k-factor world
with the real data's own loading strengths.

  If clone congruence >> real congruence  -> H1. The real data is less
     replicable than the model it was fitted with can account for.
  If clone congruence ~= real congruence  -> H2, and my reading is wrong.
     I would then have to report that the smooth decay is what a genuine
     12-factor structure looks like at this n, and drop the claim.

This is the test that can kill the finding, which is why it is run before the
finding is written down anywhere.

Run: python run_clone_test.py   ->   results_clone.json
"""
import json
import numpy as np
import pandas as pd
import mpelib as M

KS = [5, 8, 12]
N_SPLITS = 20

X, cov = M.load()
N, P = X.shape
rng = np.random.default_rng(23)
out = {'n': int(N), 'p': int(P), 'n_splits': N_SPLITS, 'ks': KS, 'cmp': {}}

for k in KS:
    L = M.loadings(X, k)                       # fitted on the FULL sample
    comm = np.clip((L ** 2).sum(1), 0, 0.99)   # communalities from the fit
    uniq = np.sqrt(1 - comm)

    # Clone: k orthogonal factor scores + item-specific noise at the fitted
    # uniquenesses. Note the clone is deliberately GENEROUS to H2 -- factors
    # are orthogonal and normal, the friendliest case for recovery.
    F = rng.standard_normal((N, k))
    Xc = pd.DataFrame(F @ L.T + rng.standard_normal((N, P)) * uniq,
                      columns=X.columns)

    real = M.split_half_congruence(X, k, n_splits=N_SPLITS, seed=300 + k)
    clone = M.split_half_congruence(Xc, k, n_splits=N_SPLITS, seed=400 + k)
    rm, cm = np.median(real, 0), np.median(clone, 0)

    out['cmp'][str(k)] = {
        'real_median': rm.tolist(), 'clone_median': cm.tolist(),
        'real_p05': np.percentile(real, 5, 0).tolist(),
        'clone_p05': np.percentile(clone, 5, 0).tolist(),
        'mean_loading_abs': float(np.abs(L).mean()),
        'max_loading_abs': float(np.abs(L).max()),
        'mean_communality': float(comm.mean()),
    }
    print(f"\nk={k}  mean|loading|={np.abs(L).mean():.3f}  "
          f"mean communality={comm.mean():.3f}")
    print("  REAL  " + " ".join(f"{v:.2f}" for v in rm))
    print("  CLONE " + " ".join(f"{v:.2f}" for v in cm))
    print(f"  factors >=.95  real:{int((rm>=.95).sum())}  clone:{int((cm>=.95).sum())}")
    print(f"  factors >=.85  real:{int((rm>=.85).sum())}  clone:{int((cm>=.85).sum())}")
    print(f"  mean phi       real:{rm.mean():.3f}  clone:{cm.mean():.3f}  "
          f"gap:{cm.mean()-rm.mean():+.3f}")

json.dump(out, open('results_clone.json', 'w'), indent=1)
print("\nwrote results_clone.json")
